- name: Play the template module
  hosts: localhost
  vars:
    dynamic_word: "World"

  tasks:
    - name: generation the hello_world.txt file
      template:
        src: template_demo.txt.j2
        dest: /Users/jyang03/projects/ansibledemo/tmp/hello_world.txt

    - name: show file context
      command: cat /Users/jyang03/projects/ansibledemo/tmp/hello_world.txt
      register: result

    - name: print stdout
      debug:
        msg: ""